### ISSUE TITLE
Hello and a request

### ISSUE THREAD

**Issue by PetricaDascalu** [ruszh96/cuda-kmeans#1]
I am very impressed with your work for the cuda-kmeans project and I want to deepen this topic more and more. 
I looked over your code and tried to follow step by step and make a much more simplified version, but I encountered a problem. I don't know what the dataset.txt dataset should look like, because it's not included among the files in the project. Do you think you could help me send this file if you still have access to it? Thank you very much!

**Comment by rustamzh** [comment]
@PetricaDascalu Personally, I do not recommend learning from this project as it was written over a day before the deadline. Here is the link to the file [Link](https://we.tl/t-yx2L566F74)

**Comment by PetricaDascalu** [comment]
I understand, thank you for your atention, i will just try to understand it and let it inspire me. Thank you!
